on: [push]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt install libdivsufsort-dev
          ./make.sh
        shell: bash
      - name: Specify rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: rustc 1.55.0-beta.3
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt install libdivsufsort-dev
          ./make.sh
        shell: bash
      - name: Specify rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: rustc 1.55.0-beta.3
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
